### ISSUE TITLE
Can't start the project

### ISSUE THREAD

**Issue by gatezh** [iPhaeton/Selectors-study#2]
After dependencies installation and running `npm start`

```
> react-boilerplate@3.4.0 start /Users/sergii/Desktop/Selectors-study-master
> cross-env NODE_ENV=development node server

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Function.listen (/Users/sergii/Desktop/Selectors-study-master/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/sergii/Desktop/Selectors-study-master/server/index.js:30:5)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-boilerplate@3.4.0 start: `cross-env NODE_ENV=development node server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-boilerplate@3.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sergii/.npm/_logs/2018-04-09T15_34_52_360Z-debug.log
```

**Comment by iPhaeton** [comment]
Looks like you have another app running at the port 3000. You can just stop that app or run e.g. `PORT=8080 npm run start` to start Selectors-study at the port 8080.

**Comment by gatezh** [comment]
Thank you!
